name: Rust

on:
  push:
    branches: [ "rust1" ]
  pull_request:
    branches: [ "rust1" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: | 
        cd rust1
        cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
